version: "3.5"
services:
  wekan:
    image: wekanteam/wekan
    environment:
      - MONGO_URL=mongodb://wekandb/wekan
      - ROOT_URL=https://wekan.looocus.run/
    # ports:
    #   - "8080"
    restart: always
    networks:
      - wekan-net
      - reverse-proxy-net
  wekandb:
    image: mongo
    volumes:
      - db-data:/data/db
    restart: always
    networks:
      - wekan-net
  redis-cli:
    image: redis:6.0-alpine
    environment:
      - SUBDOMAIN=wekan
      - ROUTING_ADDRESS=wekan:8080
    command: redis-cli -h routing-table -p 6379 set $${SUBDOMAIN} $${ROUTING_ADDRESS}
    networks:
      - reverse-proxy-net
volumes:
    db-data:
networks:
  wekan-net:
  reverse-proxy-net:
    external: true
