version: "3.5"
services:
  http-echo:
    image: hashicorp/http-echo
    # ports:
    #   - "5678:5678"
    command: "-text='hello WHABO'"
    networks:
      - reverse-proxy-net
  redis-cli:
    image: redis:6.0-alpine
    environment:
      - SUBDOMAIN=http-echo
      - ROUTING_ADDRESS=http-echo:5678
    command: redis-cli -h routing-table -p 6379 set $${SUBDOMAIN} $${ROUTING_ADDRESS}
    networks:
      - reverse-proxy-net
networks:
  reverse-proxy-net:
    external: true
