version: "3.5"
services:
  http-echo:
    image: hashicorp/http-echo
    # ports:
    #   - "5678:5678"
    command: "-text='hello WHABO'"
    networks:
      - reverse-proxy-net
networks:
  reverse-proxy-net:
    external: true
