version: '3.5'
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-net
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    # ports:
    #   - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress-net
      - reverse-proxy-net
  redis-cli:
    image: redis:6.0-alpine
    environment:
      - SUBDOMAIN=wordpress
      - ROUTING_ADDRESS=wordpress:80
    command: redis-cli -h routing-table -p 6379 set $${SUBDOMAIN} $${ROUTING_ADDRESS}
    networks:
      - reverse-proxy-net
volumes:
  db-data:
networks:
  wordpress-net:
    name: wordpress-net
  reverse-proxy-net:
    external: true
