version: "3.5"
services:
  lets-chat:
    image: sdelements/lets-chat:latest
    # ports:
    #   - 80:8080
    networks:
      - lets-chat-net
      - reverse-proxy-net
  mongo:
    image: mongo:latest
    networks:
      - lets-chat-net
  redis-cli:
    image: redis:6.0-alpine
    environment:
      - SUBDOMAIN=lets-chat
      - ROUTING_ADDRESS=lets-chat:8080
    command: redis-cli -h routing-table -p 6379 set $${SUBDOMAIN} $${ROUTING_ADDRESS}
    networks:
      - reverse-proxy-net
networks:
  lets-chat-net:
  reverse-proxy-net:
    external: true
